
name: Animal Farm NodeJS CI
on:
  push:
    branches:
      - war
  pull_request:
    branches:
      -  war

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout repo
       uses: actions/checkout@v3
     - name: java
       uses: actions/java@v5
       with:
         distribution: 'temurin' # See 'Supported distributions' for available options
         java-version: '11'
     - name: Build with Maven
       run: mvn clean package

     - name: Upload Artifact 
       uses: actions/upload-artifact@v3
       with:
          name: war-artifact
          path: target/*.war
     
